services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:1234@db:5432/ubonhooper
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: always


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ubonhooper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


  # migrate:
  #   image: node:22
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: "postgresql://admin:1234@db:5432/ubonhooper"
  #   command: >
  #     sh -c "npx prisma migrate dev --name init"